Description: >
    Fortunate Nwachukwu / Udacity Project 2

Parameters:
    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

Resources:
  LBSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our load balancer #255 characters max for description and it's required
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0

  WebServerSecGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId:
        Fn::ImportValue:
          !Sub "${EnvironmentName}-VPCID"
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
      - IpProtocol: tcp
        FromPort: 0
        ToPort: 65535
        CidrIp: 0.0.0.0/0

  WebAppLaunchConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt-get update -y
          sudo apt-get install apache2 -y
          sudo systemctl start apache2.service
          cd /var/www/html
          echo "it works! Udagram, Udacity" > index.html          
      ImageId: ami-0747bdcabd34c712a
      IamInstanceProfile:
        Fn::ImportValue: !Sub "${EnvironmentName}-IAM-NAME"
      SecurityGroups:
      - Ref: WebServerSecGroup
      InstanceType: t3.medium    # where the RAM is 4GB and CPU is 2 vCPUs | t3.large: RAM 8GB, CPU 2, Storage 20GB
      BlockDeviceMappings:
      - DeviceName: "/dev/sdk"  # This is the name of the hard drive on the VM instance
        Ebs:
          VolumeSize: '10'  # 10 GB hard drive space for the VM instance
  WebAppGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      VPCZoneIdentifier:
      - Fn::ImportValue: 
          !Sub "${EnvironmentName}-PRIV-NETS"
      LaunchConfigurationName:
        Ref: WebAppLaunchConfig
      MinSize: '3'
      MaxSize: '5'
      TargetGroupARNs:
      - Ref: WebAppTargetGroup

  WebAppLB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets:
      - Fn::ImportValue: !Sub "${EnvironmentName}-PUB1-SN"
      - Fn::ImportValue: !Sub "${EnvironmentName}-PUB2-SN"
      SecurityGroups:
      - Ref: LBSecGroup
  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
      - Type: forward
        TargetGroupArn:
          Ref: WebAppTargetGroup
      LoadBalancerArn:
        Ref: WebAppLB                
      Port: '80'
      Protocol: HTTP
  ALBListenerRule:
      Type: AWS::ElasticLoadBalancingV2::ListenerRule
      Properties:
        Actions:
        - Type: forward
          TargetGroupArn: !Ref 'WebAppTargetGroup'
        Conditions:
        - Field: path-pattern
          Values: [/]                
        ListenerArn: !Ref 'Listener'  # The ARN of the listener to which to attach the rule
        Priority: 1                   # This is the priority of the rule. The lower the number, the higher the priority.
  WebAppTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      HealthCheckIntervalSeconds: 10     # How often to check the health of the target
      HealthCheckPath: /                 # The path to check on the target
      HealthCheckProtocol: HTTP          # The protocol to use to check the health of the target
      HealthCheckTimeoutSeconds: 8       # How long to wait for a response from the target
      HealthyThresholdCount: 2           # How many consecutive successes to count as healthy
      Port: 80             
      Protocol: HTTP         
      UnhealthyThresholdCount: 5         # How many consecutive failures to count as unhealthy
      VpcId: 
        Fn::ImportValue:
          Fn::Sub: "${EnvironmentName}-VPCID" 
Outputs:
  Website:
    Value: !Sub http://${WebAppLB.DNSName}   # URL included in the README.md file of the project_starter folder
    Description: Public DNS Of LoadBalancer
    Export:
      Name: !Sub ${EnvironmentName}-Public-DNS-URL  